version: '3'
services:
    nextjs:
        image: my-nextjs-app-prod
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        restart: always
