- name: Deploy Frontend to Vercel and Set Env Variables
  hosts: localhost
  vars_files:
      - secrets.yml
  vars:
      domain_name: 'styloslingerie.com.br'
      vercel_project_name: 'stylosfront'
      env_file_path: '/home/wbruno/projects/stylosFrontEcommerce/.env' # Caminho para o arquivo .env

  tasks:
      - name: Read .env file
        ansible.builtin.slurp:
            src: '{{ env_file_path }}'
        register: env_file_content

      - name: Show content of .env file
        debug:
            var: env_file_content['content']

      - name: Decode .env file content
        set_fact:
            decoded_env: "{{ env_file_content['content'] | b64decode | to_nice_yaml }}"

      - name: Split decoded content into lines
        set_fact:
            env_lines: '{{ decoded_env.splitlines() }}'

      - name: Filter and parse valid environment variables from .env
        set_fact:
            env_vars: >-
                {{
                  env_lines
                  | select('match', '^[^#]')  # Remove comments
                  | map('split', '=')
                  | selectattr('length', '==', 2)
                  | map('first')
                  | zip(env_lines | map('last'))
                  | list
                }}

      - name: Show parsed environment variables
        debug:
            var: env_vars

      - name: Set variables from .env in Vercel
        uri:
            url: 'https://api.vercel.com/v1/projects/{{ vercel_project_name }}/env'
            method: POST
            headers:
                Authorization: 'Bearer {{ vercel_token }}'
            body: |
                {
                  "key": "{{ item.key }}",
                  "value": "{{ item.value }}",
                  "target": ["production"]
                }
            body_format: json
            status_code: 201
        loop: '{{ env_vars }}'
        when: item.key is not none

      - name: Notify user of successful deployment
        debug:
            msg: 'Vercel deployment of environment variables was successful.'
